### PR TITLE
added type support

### PR DESCRIPTION
**Pull request by noamokman**
Hi,

Added type support to enable linking directories.

Thanks!

### CODE REVIEW

**Comment by noamokman** [comment]
Hi @kevva,
I Also added a useful alias.

**Comment by noamokman** [comment]
@kevva ping 🔔

**Comment by noamokman** [comment]
@kevva?

**Comment by noamokman** [comment]
Rebased changes

**Comment by kevva** [comment]
I decided to not include the aliases, but just the `type` flag to keep it simple. Thanks!

**Pull request closed without merging**
